### PR TITLE
Added link to HF dataset

### PR DESCRIPTION
**Pull request by merveenoyan**
Hello 🙌🏻

I created this dataset repository on Hugging Face Hub (and organization page for INRIA SODA along with it): https://huggingface.co/datasets/inria-soda/tabular-benchmark. We've discussed to have it linked to this repository previously with @GaelVaroquaux.

There are cool things that come with it: dataset widget in repository, the dataset card I filled according to the paper you've published, ability to stream any dataset in this benchmark without downloading them completely, loading a dataset with simple `dataset = load_dataset("inria-soda/tabular-benchmark", data_files="reg_cat/house_sales.csv")`. The datasets can also be loaded as pandas dataset (or other formats).

Please let me know if you'd like to be added to organization, so that you can make changes as you wish on the dataset. (or simply you can give me feedback and I can edit it 🙂)

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
This is really cool. @merveenoyan , you did an amazing job consolidating the info from the paper.

I'm GaelVaroquaux on huggingface. I'd be super happy if you could add me to the org. Thanks a lot!!

**Review by GaelVaroquaux — APPROVED** [review]
LGTM. Thanks!!

**Comment by merveenoyan** [comment]
@GaelVaroquaux thanks a lot Gael 🤗 I just let you in.

**Comment by LeoGrin** [comment]
Hi @merveenoyan,

This is super cool, thanks a lot!! I'm Leogrin on huggingface, if you can add me :)

**Comment by merveenoyan** [comment]
@LeoGrin I just added you!
@GaelVaroquaux @LeoGrin I just announced it here 🙂 https://twitter.com/mervenoyann/status/1589557435995652096

**Comment by LeoGrin** [comment]
Thank you @merveenoyan !!

**Pull request merged**
